### ISSUE TITLE
_backend, _listeners being dynamically added to class

### ISSUE THREAD

**Issue by lheagy** [aranzgeo/properties#157]
I am looking leveraging `__setattr__` in a class that inherits `HasProperties` (which may or may not be a bad idea - playing at the moment! The aim would be to propagate a property to a list of classes). In doing so, I see that `_backend` and `_listeners` are being set dynamically (https://github.com/3ptscience/properties/blob/master/properties/base/base.py#L205). This could could trigger some odd behaviour if over-riding `__setattr__`. Would there be any issue making those properties of the class when it is instantiated?

**Comment by fwkoch** [comment]
@lheagy - Take a look at this: https://github.com/3ptscience/properties/pull/158

`_backend` and `_listeners` are still added dynamically since they need to be instance attributes not class attributes (and even if we set them as `@property`, we would need some underlying storage like `self.__backend` which would still call `__setattr__`). However, using `object.__setattr__` avoids calling a different `__setattr__` that may be redefined in a subclass.

Thoughts?

**Comment by fwkoch** [comment]
Or is this off the mark from your aim? I'm not sure what you mean with

> propagate a property to a list of classes.

Are you thinking more along the lines of traitlets [`add_traits`](https://github.com/ipython/traitlets/blob/4.3.2/traitlets/traitlets.py#L1329), where you dynamically add a Property to classes...?

**Comment by lheagy** [comment]
Cool thanks @fwkoch, `add_traits` is the idea I am getting at (basically `add_traits` plus an observer on that trait). My first sketchy pass at it is https://github.com/simpeg/simpeg/pull/581/files#diff-5b846c0ebd5f4af09adab86e589e5fbeR206, https://github.com/simpeg/simpeg/pull/581/files#diff-5b846c0ebd5f4af09adab86e589e5fbeR403) 
This may or may not be within the purview of the properties library. I would be happy to chat further with you. (We are also going to talk a bit about it at the SimPEG meeting today)

**Comment by fwkoch** [comment]
`Properties` is built with HasProperties classes and their properties pretty deeply tied. Most of the hooking up happens in the metaclass on class construction, so it would take major refactoring to be able to implement an `add_traits`-like method. It's not just a matter of refactoring, though, but also a matter of design. Not being able to dynamically add properties has some advantages for consistency - instances of the same class will always have the same properties. The closest we can get to is subclassing and adding/removing properties.

Regarding observers - these can be added dynamically. https://github.com/aranzgeo/properties/blob/v0.3.5/properties/handlers.py#L196
