### ISSUE TITLE
Deprecate instance `auto_create`

### ISSUE THREAD

**Issue by fwkoch** [aranzgeo/properties#162]
All the `auto_create` keyword does on `Instance` properties is set the default as the class (so it is called and therefore auto-created on initialization).

So this:
```python
my_inst = properties.Instance(
    doc='My instance',
    instance_class=SomeClass,
    auto_create=True,
)
```
is entirely equivalent to:
```python
my_inst = properties.Instance(
    doc='My instance',
    instance_class=SomeClass,
    default=SomeClass,
)
```

I don't love having two ways to do the same thing (and what happens if `auto_create` and `default` are both specified...?). Since `default` exists on all properties, I'm inclined to get rid of `auto_create`.

**Comment by rowanc1** [comment]
That sounds like a good idea.

**Comment by fwkoch** [comment]
https://github.com/3ptscience/properties/pull/164

**Comment by fwkoch** [comment]
Deprecated here: https://github.com/aranzgeo/properties/releases/tag/v0.3.4

To be removed... sometime...
