### ISSUE TITLE
`dict` property

### ISSUE THREAD

**Issue by fwkoch** [aranzgeo/properties#165]
Another possibly useful builtin property? I've used `Instance` properties with `instance_class=dict` quite a bit. Could be interesting to provide some validation on keys/values?

**Comment by bsmithyman** [comment]
Yeah, I've wondered about that. I guess I've tended to build up sub-`HasProperties` classes and then tied instances to those, but there are going to be times when it is useful to have the flexibility of a `dict`. I confess, it never _really_ occurred to me to use `dict` with `Instance`, and I wonder if that is sufficient. What sort of validation are you thinking of?

**Comment by fwkoch** [comment]
In cases where a dictionary has known set of keys, it makes sense to use another `HasProperties` instance, but for arbitrary keys, this doesn't work. It is certainly possible to just use an `Instance` property with `instance_class=dict`.

One advantage of a new property type is added validation on keys and values. An example that comes to mind - thinking along the lines of schema generation, you could do something like:
```python
class MySchema(properties.HasProperties):

    paths = properties.Dict(
        doc='Available paths and their methods',
        key_prop=properties.String('', regex='^/'),
        value_prop=properties.Instance('', SwaggerPathSpec),
    )
```

A few other advantages
- slightly less verbose do use `Dict` rather than `Instance of dict` (not that big of a deal)
- allows us to `observe_mutations` (ie `my_dict.update(...)` fires change notifications) (also probably not that big of a deal...)

Initial implementation is here https://github.com/3ptscience/properties/blob/feat/dict_prop/properties/base/containers.py - still needs some work and further discussion.

**Comment by lheagy** [comment]
A quick note to say +1 on a `Dictionary` (or `Dict`) property!

**Comment by bsmithyman** [comment]
@lheagy 
Yeah, we need to get this in: https://github.com/aranzgeo/properties/pull/188

**Comment by fwkoch** [comment]
#188 merged!
