### ISSUE TITLE
Consider how sub property types (eg on union or container) are specified

### ISSUE THREAD

**Issue by fwkoch** [aranzgeo/properties#167]
Right now either a `HasProperties` class or a `Property` instance may be specified. That means these work:
```python
a = properties.List(
    doc='list a',
    prop=properties.Integer(''),
)
b = properties.List(
    doc='list b',
    prop=MyHasPropsClass,
)
```
but these don't work:
```python
a = properties.List(
    doc='list a',
    prop=properties.Integer,
)
b = properties.List(
    doc='list b',
    prop=int,
)
```

The former doesn't work because the property must be instantiated; sometimes just the class isn't enough for that (eg `StringChoice` requires `choices` on init). But sometimes just the class is enough (eg `Integer`) - maybe this should work for those.

The latter doesn't work but I don't see any reason why it shouldn't be replaced with `properties.Instance('', int)`.

**Comment by bsmithyman** [comment]
I guess I am okay with the current behaviour...? I don't know if taking arbitrary types here & un-initialized properties is a bit too magic. That said, I don't have a really strong opinion about it.

**Comment by fwkoch** [comment]
Thanks brendan - I agree, current behaviour is fine.
