### ISSUE TITLE
Issue dilling (pickling) HasProperties classes

### ISSUE THREAD

**Issue by grosenkj** [aranzgeo/properties#171]
Using the `CofffeProfile` example class from the front page and doing the following:

```python
import dill
coffe_p = CoffeeProfile(name='John')
print('Is validated={}'.format(coffe_p.validate()))
dill.dump(coffe_p, open('test_CoffeeProfile.pkl', 'w'))
dill.load(open('test_CoffeeProfile.pkl', 'r'))
```
Results in the following output:
![image](https://cloud.githubusercontent.com/assets/6052367/25900775/719638e4-3549-11e7-8548-aa8838cd0088.png)

I am working on a freshly pulled `dev` branch.  

Shouldn't I be able to `pickle` dump and load the class directly?

**Comment by rowanc1** [comment]
Can you try with `pickle`?

```python
import pickle
coffe_p = CoffeeProfile(name='John')
print('Is validated={}'.format(coffe_p.validate()))
pickle.dump(coffe_p, open('test_CoffeeProfile.pkl', 'wb'))
pickle.load(open('test_CoffeeProfile.pkl', 'rb'))
```

It looks to me like `dill` as not triggered the startup of the class, it is missing the `_props` keys - not sure what is up there.

**Comment by grosenkj** [comment]
It works with `pickle`. 

My `pickle` interest is prompted by wanting to pickle`SimPEG` object to use with `dask`. I posted an issue on SimPEG's github https://github.com/simpeg/simpeg/issues/582. However, I do think it might be a `properties` issue since I can replicate the error with the following class. 

```python
class TestClassPickle(properties.HasProperties):
    """
    A simple test class with 2 __init__ inputs
    
        freq  - given as required property and as __init__ input
    """
    
    freq = properties.Float("frequency", min=0, required=True)
    
    def __init__(self, freq, **kwargs):
        
        self.freq = freq
        self._period = 1. / freq
```
And working with it is fine
![image](https://cloud.githubusercontent.com/assets/6052367/25910046/f95f947c-3563-11e7-8626-b352db6ce4a4.png)

but when I pickle, I get this error. 
![image](https://cloud.githubusercontent.com/assets/6052367/25910098/1259ca4c-3564-11e7-978d-7698e6de8ad4.png)

I assume the issue has something to do with the `__init__ ` method but haven't been able to figure out how to get this to work. Do you have any idea's?

**Comment by grosenkj** [comment]
I continue playing around and this works.

![image](https://cloud.githubusercontent.com/assets/6052367/25912998/15df6708-356e-11e7-9c6f-dfebfb89b0ba.png)

that is pickling a serialized version of the class and deserialize the loaded pickle object. 

Hopefully, this sheds some light on the issue.

**Comment by rowanc1** [comment]
I believe that in this case you are actually pickling up a json string, which is a bit redundant - you could just write it to disk as is.

**Comment by grosenkj** [comment]
Fair enough, but I need things to pickle to use  `dask`.

![image](https://cloud.githubusercontent.com/assets/6052367/25922955/1ec6ad5a-3590-11e7-8171-58d0323a031f.png)

This works, be adding that additional `args` check. It is a hack but it works. The issue arises in the `PropertyMetaclass.__call__` line, where it seems to me that `*args` aren't given so the call to the `obj.__init__` is missing the arguments needed. But that is beyond me. 

Thanks for the help and look forward to learning more and get it working.
