### ISSUE TITLE
properties can't be private?

### ISSUE THREAD

**Issue by lheagy** [aranzgeo/properties#191]
Mostly looking for clarification on this: what is the motivation for not allowing properties to be private? 

eg. in discretize, I am trying to create the `_cells` property as follows. It doesn't strictly need to be private, but there is minimal reason for the user to access it, so I would rather it be hidden in the namespace. 

```python
class TreeMesh(BaseTensorMesh, InnerProducts, TreeMeshIO):

    _meshType = 'TREE'

    levels = properties.Integer(
        "discretization level",
        min=0
    )

    _cells = properties.Set(
        "cells in the tree mesh",
        properties.Integer(
            "cell number",
            min=0
        ),
        default=set()
    )
```

**Comment by bsmithyman** [comment]
Hey @lheagy,
I think the idea was that if we are putting properties through various filters and such, focussing on discoverability, etc., then making them private is a bit of an anti-pattern. That said, I'm not sure of any technical reasons why it needs to be that way. I believe @fwkoch wrote that code – he may have some comments.

**Comment by lheagy** [comment]
Thanks @bsmithyman. I can see when motivated by discoverability that that would be the case. Here the motivation for employing properties for `_cells` is serialization and validation. When considering user-facing code and interacting with it from Jupyter, I would prefer to keep `_cells` out of the exposed, top-level API. We need the ability to alter and update it under-the-hood, but users shouldn't be messing with it directly. Would it be possible to accommodate this use-case?

**Comment by fwkoch** [comment]
Hi @lheagy - really exciting to see what you are doing in discretize!

Interestingly, this goes all the way back to the initial commit of properties - see here: https://github.com/aranzgeo/properties/blob/0e99c9dea0dbbc2188ecc0945cfdefd6cbafc71b/properties/base.py#L297  I haven't really given it a second thought until now.

A few considerations after dwelling on this for a couple days...

- From a technical point of view, there isn't any reason properties need to be public.

- One hesitation - I don't want to encourage using properties internal to a codebase. I really don't like the idea of someone encountering a validation error when they just ran another unrelated function. And serialization is unnecessary if a value is totally deterministic from the code. (Then again, there are arguments for using properties internally - for example, coercion could help clean up code... just the declarative nature of properties could too...)

- However, your use case for private variables is more like "advanced settings" I think, and that's much more in line with properties. I often think of users in binary terms - developers writing the properties-based code and users hacking away, looking at docs/tab-completion and reacting to validation errors. But of course there is a spectrum of user types, and private properties accounts for that.

- This is especially interesting thinking about dynamic properties - eg. user can interact with easier-to-understand properties, but those are used to set a different private property. Then only the private property is serialized.

- What about documentation? My impulse is that private properties would not be auto-documented...? Or maybe they should just fall in their own "private properties" section of the docs?

**Comment by lheagy** [comment]
Thanks Franklin! Interesting to see that it has been there from the start! 

I do agree that private variable should be used cautiously - getting unexpected errors due to variables that the user doesn't know exists is frustrating. I would argue, though, that it is on the developer to use them responsibly. 

In this use case I show above, the private variable `_cells` is enough to re-create the mesh (along with an `x0`), so for serializing, we need to have it. I would prefer it not be user-facing as it is not intuitive to work with as an array and fairly easy to corrupt the mesh in unexpected ways (we are supporting users whose primary mode of interaction is using Jupyter and completion to explore an API). In order for the user to update and work with the `_cells` array and update the mesh, we have a variety of utility functions that allow the mesh to be refined, etc. Each of these are documented and have error handling appropriate for each use case - these are what I would like to encourage users to be using. Working directly with the `_cells` would really only be recommended for an advanced user. 

Documentation is an interesting question - it isn't really standard practice to document private variables, but I do like the idea of a `**Private-Properties (Advanced)**` section in the docs (or some way to clearly indicate that the user should think twice before messing with these) to promote discoverability and transparency in the code.

**Comment by bsmithyman** [comment]
Separating out the `_` props in the docs would work from my point of view. Exact language could be worth thinking on ("Unsupported", "Internal", "Advanced", "Private", etc.).

**Comment by fwkoch** [comment]
@lheagy - re: "on the developer to use them responsibly" - I agree wholeheartedly on this. Arbitrarily eliminating this option for developers is not very pythonic.

@bsmithyman - I was thinking a flag like your first code snippet is one possibility. I think this would be a great idea for choosing whether or not to display private properties in the docs (we already have a "secret" flag for specifying doc order, so there is precedent). I'm a bit hesitant on an absolute flag for allowing private properties (or not) for a couple reasons - (1) not sure what the default should be, (2) if someone is using private properties, then so be it, I don't really want to frustrate a developer and make them dig in the docs for how to activate private props...

**Comment by bsmithyman** [comment]
@fwkoch: Right, so take the restriction out, but hide things from the docs by default. A flag that is set on a base class would propagate the setting to all subclasses, so it lets developers decide to use non-default behaviour wherever they want in the hierarchy. Sounds good to me.

**Comment by fwkoch** [comment]
Talked this over a bit with @rowanc1 - Original motivation for this was taken from `ndb properties` which does not allow private properties. I think the reasoning there is that much more is going on in the private namespace with `ndb`, so reserving private for internal use and public for external use makes some sense. In `properties`, we try to minimize what is going on (both private and public) so it makes less sense to impose this restriction.

Let's remove this restriction in the next release (unless something else unexpected comes up...).

**Comment by rowanc1** [comment]
Yeah, thanks for commenting @fwkoch. The example I based this on is here:

https://github.com/GoogleCloudPlatform/datastore-ndb-python/blob/8f0895e5a01aa4387c01fec1d2644d5a084961eb/ndb/model.py#L3331

Looking forward to seeing this restriction removed.

**Comment by fwkoch** [comment]
See #194

**Comment by fwkoch** [comment]
These features are supported in `properties>=0.3.6b0`
