### ISSUE TITLE
Array's can't be complex

### ISSUE THREAD

**Issue by grosenkj** [aranzgeo/properties#208]
I am using `Array` to store a ndarray of `dtype=complex`, which is not allowed. 

Is there a reason why an array can't be `complex` dtype? 
If there isn't any, can this be added as an allowed type?

**Comment by fwkoch** [comment]
I don't see any problem adding more `dtype`s to `Array`. Should just be a matter of updating `TYPE_MAPPINGS` https://github.com/aranzgeo/properties/blob/v0.3.5/properties/math.py#L13

**Comment by grosenkj** [comment]
Ok, that is easy enough. I will put together a pull request. 

Will the testing need to be updated as well?

**Comment by fwkoch** [comment]
That would be wonderful, if you are up for it! At least a sanity check. Tests aren't particularly beautiful, but I'd probably just add a `dtype=complex` array here, and make sure it works as expected. https://github.com/aranzgeo/properties/blob/v0.3.5/tests/test_math.py#L28

**Comment by grosenkj** [comment]
Finally had the chance to sort out a pull request, see #215.

On my end, things are working as intended so I will close this issue. Let me know if there is anything else I can/need to do on this.

Thanks for the help
