### ISSUE TITLE
Deserialize and coerce list

### ISSUE THREAD

**Issue by rowanc1** [aranzgeo/properties#211]
When trying to deserialize a string, which should be coerced into a list, there seems to be a bug.

```python
class Number(properties.HasProperties):
    count = properties.List(
        'count',
        properties.StringChoice(
            "",
            choices={'one', 'two', 'three'}
        ),
        coerce=True
    )
```

```python
assert(isinstance(Number(count='one').count, list))  # coerce works
Number.deserialize(dict(count='one')) # errors with 'o' not in {'one', 'two', 'three'}
```
The exception is:
```
ValueError: The List property 'count' of a Number instance
must be a list (each item is any of "three", "one", "two"). 
A value of 'o' <class 'str'> was specified. This is an invalid list item.
```

Probably there is a `list(value)` instead of `[value]`.

**Comment by fwkoch** [comment]
Thanks @rowanc1 - my take is this isn't a bug, but that relies on my subtle, undocumented interpretation of serialization/deserialization vs. validation/coercion (and is certainly up for discussion).

__Validation__ and coercion happen on input of `Property` values and on `validate()`. This is taking "human-accessible" user input and ensuring it is the "valid" type.

**Serialization** takes the _valid_ `HasProperties` class and converts it to something that can be saved to a file. Deserialization is the reverse of that process, and in my opinion, should be used only on serialization's output.

With simple properties like strings, validation and serialization pretty much look like the same thing. User input, valid value, and saveable-to-file value are all just the same string. However, the differences are apparent with more complicated properties like `Array` - in that case, user input may be a list or a numpy array, valid type is a numpy array, and serialized value may be a binary file or something. **Validate** needs to deal with the user input whereas **deserialize** needs to deal with the binary file.

So, looking at your example,

```python
Number.deserialzie(dict(count='one')) # should not be used.

# Instead, if you want to focus on validating user input in a dictionary:
Number(**dict(count='one')) # This will validate.

# Or, if you want to deserialize, only do so from a serialized value:
Number.deserialize(Number(count='one').serialize())
```

My takeaway is that these interpretations of validation vs. serialization should be explicit in the docs. There could also possibly be better error handling on deserialize?

Do you have any additional thoughts on this?

**Comment by bsmithyman** [comment]
I am pretty happy with having `.deserialize(...)` be strict, and focussing the user interface on the base constructor. Do you think there is demand for a deserialize-like constructor method that mixes these two behaviours?

_NB: We have other internal code that may be affected by this, so we should high-grade the discussion if changes are going to be made._

**Comment by rowanc1** [comment]
I like the distinction you make @fwkoch. I agree that the saved JSON should be valid, and not coerced on the way in. Your comment about this distinction should probably make it into the docs!
