### ISSUE TITLE
properties 4.0 breaks optional lists

### ISSUE THREAD

**Issue by timmclennan** [aranzgeo/properties#226]
I was using omf + steno3d and pip updated to the latest version which install properties version 0.4.
My example stopped working because it wouldn't handle ProjectElements with no data list.

Tracing it back it appears to be an issue inside of properties.
In particular the following code fragment works different in versions 0.4 and 0.3.5
```python
import properties
print properties.__version__

class AnObject(properties.HasProperties):
    pass

class TestList(properties.HasProperties):
    the_list = properties.List('test_list', prop=AnObject, required=False)
print TestList().the_list
```
In 0.4 it produces
```
0.4.0
None
```
while in 0.3.5 it produces
```
0.3.5
[]
```
This was running on a Windows 64bit  python2.7 Anaconda distribution.

**Comment by fwkoch** [comment]
Thanks - this a known backwards incompatibility - See here: https://github.com/aranzgeo/properties/releases/tag/v0.4.0

The `omf` library needs to be updated for properties v0.4.0 - See here: https://github.com/GMSGDataExchange/omf/pull/24

**Comment by fwkoch** [comment]
OMF has now been updated - https://github.com/GMSGDataExchange/omf/releases/tag/v0.9.2
