### ISSUE TITLE
sphinx docs vs plain text docs

### ISSUE THREAD

**Issue by fwkoch** [aranzgeo/properties#8]
All the nice markup features that make the sphinx docs look good cause the plain text docstrings (those accessed by `?` in the notebook) to look messy. As we start linking docs with intersphinx, things get more and more complicated.

Should we somehow separate these into two different docstrings, sphinx and plain text?

**Comment by rowanc1** [comment]
You can check if you are in IPython and return a better doc string:

```python
def run_from_ipython():
    try:
        __IPYTHON__
        return True
    except NameError:
        return False
```

Can you separate out the doc string type `sphinx` vs something perhaps more like `napolean`? Which is much more readable, and I believe has all the same functionality.

http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by lheagy** [comment]
I have been playing around with this a bit as well and will add my 2 cents 

The plain text in the notebook is tricky to sort through with all of the formatting in there. Standard sphinx still has a bit of formatting (but I am more used to seeing that, so it is less of a concern for me personally), or within the notebook environment, I like the plain-text style that scipy uses 

![image](https://cloud.githubusercontent.com/assets/6361812/24112517/068bd0f0-0d57-11e7-9f72-b0f52ff10951.png)

It is also resulting in the duplication of variables when I build sphinx documentation for classes that use properties, which has the potential to cause confusion. 

![image](https://cloud.githubusercontent.com/assets/6361812/24112707/ad78bce8-0d57-11e7-88ed-4ce796c3eba2.png)

**Comment by fwkoch** [comment]
There is a small check for `__IPYTHON__` to determine if intersphinx class refs should be added or not: https://github.com/aranzgeo/properties/blob/dev/properties/basic.py#L350

Regarding duplication in the docs - I think this is a matter of being picky with how you `.. autoclass::` things in sphinx. Maybe do not document all `:members:` but instead, be explicit about the ones you want (probably the non-properties ones).
