### ISSUE TITLE
Note what's needed to write a backend

### ISSUE THREAD

**Issue by bsmithyman** [aranzgeo/properties#88]
- In docs

**Comment by fwkoch** [comment]
Just to expand on this issue a bit: Currently, `_backend` is a `dict`. In the future, this class may be swappable. When that is the case, the class used for `_backend` must behave somewhat like a dictionary by implementing `__setitem__`, `__getitem__`, `get`, and `pop`.

For now, though, this is on hold.

**Comment by fwkoch** [comment]
We need a much higher level discussion: https://github.com/aranzgeo/properties/issues/220
